aroha:
  - S - - g - - M - - d - - n - - S. - -
avroha:
  - S. - - n - - d - - M - -, g - - M:g - - S - -
pakad:
  - g - - M - g - - S - -, .d - - .n - S - -
swarmaalika:
  - sam: 9
  - mukra:
      -
  - sthayi:
      - lineA:
          - :S. n:S. d - - M:g M:d:M:g M:d:n:S. n:S. n:S. d - - M:g M:d:M:g S:S
      - lineB:
          - :.d :.n S:M M:M g M:d M:d:M:g S:.n S:M g:M d M:n :d S.:S. S.:g.:S.:n
  - antara:
      - lineC:
          - :S. S:g M:d :n S. S.:S. n:n S.:g. S.:g.:S.:n d:d n:S. g.:S. g.:M. g.:S. d:n S.:g. S.:n
      - lineD:
          - d d M:g M:g n:S. g:M d:n d:n d:n:S.:g. M.:g.S.:n S.:S.
  - tihayi:
      -