alankars:
  - sa re ga pa dha sa. sa. dha pa ga re sa
  - sa ga re pa ga dha pa sa. sa. pa dha ga pa re ga sa
aroha:
  - sa re ga pa dha sa. -
avroha:
  - sa. dha pa ga re sa -
pakad:
  - ga re sa .dha, sa re ga, pa ga dha pa, ga re sa
sthayi:
  - ga re sa .dha, sa re ga, pa ga dha pa, ga re sa
antara:
  - ga re sa .dha, sa re ga, pa ga dha pa, ga re sa
