alankars:
  - S R G P D S. S. D P G R S
  - S G R P G D P S. S. P D G P R G S
aroha:
  - S R G P D S. -
avroha:
  - S. D P G R S -
pakad:
  - G R S .D, S R G, P G D P, G R S
sthayi:
  - G R S .D S R G P G D P, G R S
antara:
  - G R S .D S R G P G D P, G R S
