alankars:
  - S R M P D S. S. D P M R S
  - S M R P M D P S. S. P D M P R M S
aroha:
  - S R M P D S. -
avroha:
  - S. D P M R S -
pakad:
  - M P D -, M R -, .D .D S - -
sthayi:
  - S. - S. D - D M P D M R S
  - .D S R S:R M - R M P M:P D -
antara:
  - M - M P - P D S. - S. D S.
  - R. M. R. S. - D M P D M R S
