alankars:
  - sa re ma pa dha sa. sa. dha pa ma re sa
  - sa ma re pa ma dha pa sa. sa. pa dha ma pa re ma sa
aroha:
  - sa re ma pa dha sa. -
avroha:
  - sa. dha pa ma re sa -
pakad:
  - ma pa dha -, ma re -, .dha .dha sa - -
sthayi:
  - sa. - sa. dha - dha ma pa dha ma re sa
  - .dha sa re sa re ma re ma pa ma pa dha
antara:
  - ma - ma pa - pa dha sa. - sa. dha sa.
  - re ma re sa. dha - ma pa dha ma re sa
