alankars:
  - S R M P D S. S. D P M R S
  - S M R P M D P S. S. P D M P R M S
aroha:
  - S - R - M - P - D - S. - -
avroha:
  - S. - D - P - M - R - S - -
pakad:
  - P/M - P D -, P/M - R -, S/.D - .D - S - -
swarmaalika:
  - sam: 1
  - mukra:
    -
  - sthayi:
    - lineA:
      - S. - S. D - D M P D M R S
    - lineB:
      - .D S R S:R M - R M P M:P D -
  - antara:
    - lineC:
      - M - M P - P D S. - S. D S.
    - lineD:
      - R. M. R. S. - D M P D M R S
  - tihayi:
      - S. - S. D - D
