alankars:
  - S R G P N S. S. N P G R S
  - S G R P G N P S. S. P N G P R G S
aroha:
  - S R G P N S. -
avroha:
  - S. N P G R S -
pakad:
  - .P .N S R -, R G P - R -, R - G S -
sthayi:
  - .P .N S R - R G P - R - R - G S -
antara:
  - .P .N S R - R G P - R - R - G S -
