alankars:
  - sa re aa pa ni sa. sa. ni pa ga re sa
  - sa ga re pa ga ni pa sa. sa. pa ni aa pa re ga sa
aroha:
  - sa re ga pa ni sa. -
avroha:
  - sa. ni pa ga re sa -
pakad:
  - .pa .ni sa re -, re ga pa - re -, re - ga sa -
sthayi:
  - .pa .ni sa re -, re ga pa - re -, re - ga sa -
antara:
  - .pa .ni sa re -, re ga pa - re -, re - ga sa -
