aroha:
  - S - - g - - M - - d - - n - - S. - -
avroha:
  - S. - - n - - d - - M - -, g - - M:g - - S - -
pakad:
  - g - - M - g - - S - -, .d - - .n - S - -
swarmaalika:
  - sam: 9
  - mukra:
      -
  - sthayi:
      - lineA:
          - S. g. S. S. d M d n S. - - d n d M M
      - lineB:
          - g g g M:d n:S. n S. - g - M d M g S -
  - antara:
      - lineC:
          - g g g g M M d n S. - S. S. n S. S. -
      - lineD:
          - n n n - S. - S. S. d M d n d M M -
      - lineE:
          - g g g M:d n:S. n S. - g - M d M g S -
  - tihayi:
      - S. g. S. S. d M d n