alankars:
  - .ni re ga ma' pa dha ni sa. sa. ni dha pa ma' ga re sa
  - .ni ga re ma' ga pa ma' dha pa ni dha sa. sa. dha ni pa dha ma' pa ga ma' re ga sa
aroha:
  - .ni re ga ma' pa dha ni sa. -
avroha:
  - sa. ni dha pa ma' ga re sa -
pakad:
  - .ni re - ga re sa -, pa ma' - ga re sa -
sthayi:
  - .ni re - ga re sa -, pa ma' - ga re sa -
antara:
  - .ni re - ga re sa -, pa ma' - ga re sa -